replicaCount: 1

image:
  repository: data-processor
  tag: latest
  pullPolicy: Never

serviceAccount:
  create: false
  name: ""

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false

service:
  type: ClusterIP
  port: 80